stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    - git remote add github https://shaninalex:${GH_TOKEN}@github.com/shaninalex/Lumna.git
    - git push github HEAD:refs/heads/main --force
  only:
    - main
